import React from 'react';

import Head from 'next/head';
import { client } from '../Lib/client';
import { Product, FooterBanner, HeroBanner, ContactForm } from '../componets';

const Home = ({ products, bannerData}) => {
  return (
   <>
     <Head>
        <title>Christina Maria Designs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    <HeroBanner heroBanner={bannerData.length && bannerData[0]} />


    <FooterBanner footerBanner={bannerData && bannerData[0]} />
    <ContactForm />
   </>
  )
}


export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);

  const bannerQuery = '*[_type == "banner"]';
  const bannerData = await client.fetch(bannerQuery);

  return {
    props: { products, bannerData }
  }
}

export default Home
